"""WebSocket message type definitions."""

# Client -> Server messages
MSG_HEARTBEAT = "heartbeat"
MSG_BOUNCE_ADD = "bounce_add"
MSG_BOUNCE_REMOVE = "bounce_remove"
MSG_CONNECT = "connect"
MSG_DISCONNECT = "disconnect"
MSG_SCREEN_ACTION = "screen_action"
MSG_RUN_TOOL = "run_tool"
MSG_SET_TOOL_TARGET = "set_tool_target"
MSG_STOP_TOOL = "stop_tool"
MSG_SET_SPEED = "set_speed"
MSG_ACCEPT_MISSION = "accept_mission"
MSG_COMPLETE_MISSION = "complete_mission"
MSG_BUY_SOFTWARE = "buy_software"
MSG_BUY_HARDWARE = "buy_hardware"
MSG_BUY_STOCK = "buy_stock"
MSG_SELL_STOCK = "sell_stock"
MSG_TAKE_LOAN = "take_loan"
MSG_REPAY_LOAN = "repay_loan"
MSG_TRANSFER_FUNDS = "transfer_funds"
MSG_LAN_ACTION = "lan_action"
MSG_CHOOSE_SIDE = "choose_side"
MSG_COMPLETE_SPECIAL_MISSION = "complete_special_mission"
MSG_MARK_READ = "mark_read"

# Server -> Client messages
MSG_HEARTBEAT_ACK = "heartbeat_ack"
MSG_BOUNCE_CHAIN_UPDATED = "bounce_chain_updated"
MSG_CONNECTED = "connected"
MSG_DISCONNECTED = "disconnected"
MSG_SCREEN_UPDATE = "screen_update"
MSG_TASK_UPDATE = "task_update"
MSG_TASK_COMPLETE = "task_complete"
MSG_TRACE_UPDATE = "trace_update"
MSG_TRACE_COMPLETE = "trace_complete"
MSG_BALANCE_CHANGED = "balance_changed"
MSG_RATING_CHANGED = "rating_changed"
MSG_MESSAGE_RECEIVED = "message_received"
MSG_SPEED_CHANGED = "speed_changed"
MSG_GAME_OVER = "game_over"
MSG_ERROR = "error"
MSG_GAME_TIME = "game_time"
MSG_LAN_UPDATE = "lan_update"
MSG_PLOT_UPDATE = "plot_update"
MSG_NEWS_UPDATE = "news_update"
MSG_STOCK_UPDATE = "stock_update"
MSG_GATEWAY_UPDATED = "gateway_updated"
MSG_PLAYER_UPDATED = "player_updated"
